---
title: "Current Professional Activities"
---

<br>

Within the Department of Statistics and Actuarial Science at Waterloo:

* Since January 2025 I have been co-organizing (with [Megan French](https://uwaterloo.ca/statistics-and-actuarial-science/contacts/megan-french)) a [Student Seminar Series](https://uwaterloo.ca/statistics-and-actuarial-science/student-seminar-series) designed to give grad students an opportunity to present their research.
We also occasionally invite professors to introduce their work to a student audience.
  - If you are interested in giving a talk, please [reach out](mailto:lsbumbul@uwaterloo.ca; me2french@uwaterloo.ca?subject=SAS Student Seminar Series)!
* In June 2025 I began a two-year term as a grad student co-representative (with [Diribsa Bedada](https://uwaterloo.ca/statistics-and-actuarial-science/contacts/diribsa-tsegaye-bedada)).
We facilitate communication between students, faculty, and staff in the department and represent the student perspective at department meetings.

Beyond the department:

* In May 2025 I began a one-year term as Waterloo's representative in the [CANSSI Student PhD and Research Network (SPARK) Group](https://canssiontario.utoronto.ca/2025-2026-spark-group/).

<!--
* During the first year of my PhD I served as a SAS department representative on the [Women in Mathematics Committee](https://uwaterloo.ca/women-in-mathematics/committee).
  - In this role I co-organized the 2025 [Navigating Your Careers Conference](https://uwaterloo.ca/women-in-mathematics/navigating-your-careers-nyc-conference) in Waterloo, ON, and the 2025 [Ontario Graduate Mathematics Conference](https://uwaterloo.ca/women-in-mathematics/ontario-graduate-mathematics-conference) in Toronto, ON.
-->

