---
title: "Teaching"
---

<br>
My teaching experience relates to several statistics (STAT) courses offered by the University of Waterloo.
A list of STAT courses with short descriptions can be found here: [\[undergraduate\]](https://ucalendar.uwaterloo.ca/2324/COURSE/course-STAT.html); [\[graduate\]](https://academic-calendar-archive.uwaterloo.ca/graduate-studies/archive-spring-2021/graduate-course/subject/STAT.html).
<br><br>

## Guest Lectures and Exam Reviews

<b>STAT 450: Estimation and Hypothesis Testing,</b> Winter 2025<br>
Instructor: [Prof. Peter W. MacDonald](https://peterwmacd.github.io/)

* Guest lecture on Bayesian estimation (50 mins)
<br>

<b>STAT 850: Estimation and Hypothesis Testing (Graduate-Level),</b> Fall 2024<br>
Instructor: [Prof. Yingli Qin](https://www.math.uwaterloo.ca/~y34qin/)

* Two final exam review sessions (3 hours each)

## Teaching Assistantships

<b>STAT 231: Statistics,</b> Spring 2025<br>
<b>STAT 230: Probability (Online),</b> Winter 2025<br>
<b>STAT 450: Estimation and Hypothesis Testing,</b> Winter 2025<br>
<b>STAT 330: Mathematical Statistics,</b>  Fall 2024$^\dagger$<br>

<small>
  $^\dagger$ <em>Received Department of Statistics and Actuarial Science TA Award</em>
</small>

## Credentials

<b>Foundations for University Teaching in Statistics and Actuarial Science Certificate</b>
<br>
<div style="height: 0.5em;"></div>
To earn this certificate, graduate students in the University of Waterloo's Department of Statistics and Actuarial Science are required to attend at least six workshops
(two run by the department and at least four run by the university's [Centre for Teaching Excellence](https://uwaterloo.ca/centre-for-teaching-excellence/))
and complete two teaching practicums observed by a member of the department's [TA Program](https://uwaterloo.ca/statistics-and-actuarial-science/graduate-studies/graduate-student-resources/teaching-assistants-program).
<br>
<br>
My first practicum involved running a 50-minute tutorial on random variable transformations (STAT 330, Fall 2024).
My second practicum involved designing and running a two-hour review session on finding maximum likelihood, method of moments, and Bayesian estimators and evaluating their efficiency (STAT 450, Winter 2025).
Both were observed by [Prof. Reza Ramezan](https://sites.google.com/site/ramezanic/home).
<br>
<br>
More information about the certificate can be found [here](https://uwaterloo.ca/statistics-and-actuarial-science/graduate-studies/resources-students/teaching-assistants-program/training-and-development).


